### PR TITLE
Django 2 support

### PR DESCRIPTION
**Pull request by EliotBerriot**
This should bring compatibility with Django 1.11 (and greater). Let we know what you think about it ;)

(you can try it with `pip install git+https://github.com/EliotBerriot/django-simple-math-captcha.git@django-2-support`)

### CODE REVIEW

**Comment by alsoicode** [comment]
Thank you very much for your work. I'll try to get a new release out to PyPi today.

**Comment by EliotBerriot** [comment]
Oh, thanks, I hope it works as expected :D (it will likely break compatibility with django <1.11, but this version is already quite old, so I don't think it should block anything :)

**Comment by alsoicode** [comment]
I agree. 1.1x is very old and folks using that should definitely update.

**Comment by alsoicode** [comment]
Ok, 1.0.8 is now available on PyPi

**Comment by EliotBerriot** [comment]
That was fast @alsoicode, thank you!

**Comment by alsoicode** [comment]
You're very welcome, and thanks again for the pull request.

**Pull request merged**
